### PR TITLE
fixed a typo on route.rb

### PR DESCRIPTION
**Pull request by apires89**
@CelsoBenidio @AVanLaere @mukhambetzhanov  @egecancitim @gitwithuli 
just fixed a typo on routes.
ex:
started on css
created controller for stores

### CODE REVIEW

**Comment by gitwithuli** [comment]
saw

**Comment by egecancitim** [comment]
nice catch!

**Comment by apires89** [comment]
thank you so much

**Comment by gitwithuli** [comment]
anytime bro

**Pull request merged**
